// Regenerate app/gui.css — the whole @hanzo/gui atomic sheet, as a real static asset.
//
// gui builds its atomic CSS as components are constructed, so the sheet only exists
// once something has rendered. The obvious way to get it into a statically exported
// document is useServerInsertedHTML — and that was the bug: Next runs that callback
// on EVERY streaming flush and getCSS() returns the entire accumulated sheet each
// time, so hanzo.ai's homepage shipped thirteen byte-identical copies, 591,305 of
// its 638,443 bytes. Inline, it is also uncacheable and re-sent on every navigation.
//
// Generating it here instead makes it an ordinary stylesheet: Next fingerprints it,
// the browser caches it once, and every page after the first pays nothing. GuiProvider
// renders with disableInjectCSS so this file is the ONE source of gui styles.
//
// Wired to `prebuild`, so it cannot drift from lib/gui.ts.
//
// IT IS `css()`, NEVER `config.getCSS()`. gui declares every theme key as a bare
// `--<key>` on its root themes, and three of those names — background, black,
// white — are @hanzo/design's. `:root.t_dark` is (0,2,0) and beats design outright;
// plain `:root` ties it and wins on load order, because this sheet is imported
// last. So gui's grey shipped over design's black and no CSS in this repo could
// reach it. `css()` in @hanzo/ui/gui-config drops exactly those declarations from
// exactly the ROOT themes (a nested `.t_dark_Button` legitimately scopes its own
// ground and is left alone); the TOKEN survives, `$background` still compiles to
// `var(--background)`, and that var now reads design's value from the cascade —
// so the ground follows the brand, the theme and any runtime retune.
//
// The prune lives in the package because every app runs a generator of its own,
// and a copy per app is how one of them keeps shipping the shadowed sheet. This
// script's whole job is to call it and write the bytes.
import { execFileSync } from 'node:child_process'
import { writeFileSync, rmSync } from 'node:fs'

const bundle = new URL('../.guicfg.gen.mjs', import.meta.url)

// lib/gui.ts is TypeScript and pulls in the @hanzogui graph, so it has to be
// bundled before Node can import it. react-native is aliased to react-native-web
// for the same reason the Next build does it: the bare specifier resolves to the
// native implementation, which has no business running here.
execFileSync(
  'esbuild',
  [
    'lib/gui.ts',
    '--bundle',
    '--format=esm',
    '--platform=node',
    '--external:react',
    '--external:react-dom',
    '--external:react-native',
    '--alias:react-native=react-native-web',
    `--outfile=${bundle.pathname}`,
    '--log-level=error',
  ],
  { stdio: 'inherit', cwd: new URL('..', import.meta.url).pathname },
)

const { css } = await import(bundle)
// The banner is not decoration: `hanzo-design-lint` skips a file whose head says
// it is generated, and without it the whole gui sheet is linted as source — a
// build product reported for raw colour, which is an instruction to hand-edit
// the output of a generator.
const sheet = `/* AUTO-GENERATED by scripts/gen-gui-css.mjs from lib/gui.ts — DO NOT EDIT. */\n${css()}`
writeFileSync(new URL('../app/gui.css', import.meta.url), sheet)
rmSync(bundle)
console.log(`app/gui.css regenerated — ${sheet.length.toLocaleString()} bytes`)
